/*
 * some code fix and or generated by chatgpt with manual checked and run 
 */

import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.Callable;

/**
 *
 * @author dedetok
 */
public class CallableCheckUrlItem implements Callable<RadioListItem> {
    private final RadioListItem myListItem;
    
    public CallableCheckUrlItem(RadioListItem myListItem) {
        this.myListItem = myListItem;
    }

    @Override
    public RadioListItem call() {
        myListItem.mIconStatus=checkUrlImage(myListItem.mIcon);
        myListItem.mStreamStatus=checkRadioStream(myListItem.mStreamURL);
        return myListItem; // Return the modified or original RadioListItem as needed
    }
    
    private String checkUrlImage(String myUrlString) {
        int responseCode=-1;
        HttpURLConnection connection=null;
        try {
            URL url = new URL(myUrlString);
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("HEAD"); // Use HEAD to avoid downloading the content
            connection.setConnectTimeout(3000);
            connection.setReadTimeout(3000);
            connection.setRequestProperty("User-Agent", "Mozilla/5.0");
            // Connect and get response code
            connection.connect();
            responseCode = connection.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                return "200"; // or any other indication of success
            } else {
                return "Error: " + responseCode; // return the error code
            }
        } catch (MalformedURLException ex) {
            return ex.getMessage();
        } catch (IOException ex) {
            return ex.getMessage();
        } finally {
            if (connection != null) {
                connection.disconnect(); // ✅ frees the network resources
            }
        }
    }

    private String checkRadioStream(String urlString) {
        HttpURLConnection con = null;

        try {
            URL url = new URL(urlString);
            con = (HttpURLConnection) url.openConnection();

            con.setConnectTimeout(3000); // fast timeout
            con.setReadTimeout(3000);
            con.setRequestMethod("GET");
            con.setRequestProperty("User-Agent", "Mozilla/5.0");

            // Helps Icecast/Shoutcast servers respond correctly
            con.setRequestProperty("Icy-MetaData", "1");

            // Get HTTP code
            int code = con.getResponseCode();
            if (code != HttpURLConnection.HTTP_OK) {
                return "200";
            }

            // Read only **1 byte** from stream (very, very fast)
            InputStream in = con.getInputStream();
            if (in.read() != -1) { // if we get 1 byte → stream is alive
                return "200";
            } else {
                return "NO STEAM";
            } 
        } catch (IOException e) {
            return e.getMessage();
        } finally {
            if (con != null) con.disconnect();
        }
    }
    
}
