/*
 * some code fix and or generated by chatgpt with manual checked and run 
 */

import java.io.Serializable;

/**
 *
 * @author dedetok
 */
public class RadioListItem implements Serializable {

    private static final long serialVersionUID = 1L;

    public String mCountry;   // 0
    public String mCity;      // 1
    public String mRadio;     // 2 
    public String mIcon;      // 3 url string
    public String mStreamURL; // 4 url string
    public String mIconStatus; // respon
    public String mStreamStatus; // respon
            

}
